#!/usr/bin/env node
/**
 * Embed gmCli/dist/index.html into src/gmWebShow.erl as one Erlang binary literal.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const htmlPath = path.join(root, "gmCli", "dist", "index.html");
const outPath = path.join(root, "src", "gmWebShow.erl");

if (!fs.existsSync(htmlPath)) {
  console.error("Missing", htmlPath, "- run gmCli build first");
  process.exit(1);
}

const html = fs.readFileSync(htmlPath);

/** Escape bytes for <<" ... ">> in Erlang source. */
function escapeErlangBinary(buf) {
  let out = "";
  for (let i = 0; i < buf.length; i++) {
    const b = buf[i];
    if (b === 92) out += "\\\\";
    else if (b === 34) out += '\\"';
    else if (b === 10) out += "\\n";
    else if (b === 13) out += "\\r";
    else if (b === 9) out += "\\t";
    else if (b >= 32 && b <= 126) out += String.fromCharCode(b);
    else out += `\\x${b.toString(16).padStart(2, "0")}`;
  }
  return out;
}

const erl = `%% AUTO-GENERATED by scripts/embed_frontend.mjs — do not edit by hand.
-module(gmWebShow).

-export([indexHtml/0, contentType/0]).

-spec indexHtml() -> binary().
indexHtml() ->
    <<"${escapeErlangBinary(html)}">>.

-spec contentType() -> binary().
contentType() ->
    <<"text/html; charset=utf-8">>.
`;

fs.writeFileSync(outPath, erl);
console.log(`Wrote ${outPath} (${html.length} bytes embedded)`);
